using UnityEngine;
using UnityEditor;
using System;
using System.Reflection;
using System.Collections;

namespace ZeroEngine.Editor
{
    /// <summary>
    /// YooAsset 一键配置工具
    /// 使用反射调用 YooAsset API，无硬依赖
    /// </summary>
    public static class YooAssetSetup
    {
        /// <summary>
        /// 一键配置 YooAsset 规则
        /// </summary>
        public static void SetupDefaultRules()
        {
            Debug.Log("[ZeroEngine] Configuring YooAsset Rules via API...");

            // 确保 Assets/Data 文件夹存在
            if (!AssetDatabase.IsValidFolder("Assets/Data"))
            {
                AssetDatabase.CreateFolder("Assets", "Data");
                Debug.Log("[ZeroEngine] Created 'Assets/Data' folder.");
            }

            try
            {
                // 获取 AssetBundleCollectorSettingData 类型
                var settingDataType = GetType("YooAsset.Editor.AssetBundleCollectorSettingData");
                if (settingDataType == null)
                {
                    Debug.LogError("[ZeroEngine] Cannot find YooAsset.Editor.AssetBundleCollectorSettingData. Is YooAsset installed?");
                    return;
                }

                // 获取 Setting 属性
                var settingProp = settingDataType.GetProperty("Setting", BindingFlags.Public | BindingFlags.Static);
                var setting = settingProp?.GetValue(null);
                if (setting == null)
                {
                    Debug.LogError("[ZeroEngine] YooAsset Setting is null. Try opening YooAsset window manually first.");
                    EditorApplication.ExecuteMenuItem("YooAsset/AssetBundle Collector");
                    return;
                }

                // 获取 Packages 列表
                var packagesField = setting.GetType().GetField("Packages", BindingFlags.Public | BindingFlags.Instance);
                var packages = packagesField?.GetValue(setting) as IList;

                if (packages == null)
                {
                    Debug.LogError("[ZeroEngine] Cannot access Packages list.");
                    return;
                }

                // 检查 DefaultPackage 是否存在
                object defaultPackage = null;
                foreach (var pkg in packages)
                {
                    var nameField = pkg.GetType().GetField("PackageName", BindingFlags.Public | BindingFlags.Instance);
                    if (nameField != null && (string)nameField.GetValue(pkg) == "DefaultPackage")
                    {
                        defaultPackage = pkg;
                        break;
                    }
                }

                // 如果不存在则创建 DefaultPackage
                if (defaultPackage == null)
                {
                    var packageType = GetType("YooAsset.Editor.AssetBundleCollectorPackage");
                    defaultPackage = Activator.CreateInstance(packageType);
                    var nameField = packageType.GetField("PackageName", BindingFlags.Public | BindingFlags.Instance);
                    var descField = packageType.GetField("PackageDesc", BindingFlags.Public | BindingFlags.Instance);
                    nameField?.SetValue(defaultPackage, "DefaultPackage");
                    descField?.SetValue(defaultPackage, "Auto-generated by ZeroEngine");
                    packages.Add(defaultPackage);
                    Debug.Log("[ZeroEngine] Created 'DefaultPackage'");
                }

                // 获取 Groups 列表
                var groupsField = defaultPackage.GetType().GetField("Groups", BindingFlags.Public | BindingFlags.Instance);
                var groups = groupsField?.GetValue(defaultPackage) as IList;

                // 检查 GameData 组是否存在
                object dataGroup = null;
                if (groups != null)
                {
                    foreach (var grp in groups)
                    {
                        var nameField = grp.GetType().GetField("GroupName", BindingFlags.Public | BindingFlags.Instance);
                        if (nameField != null && (string)nameField.GetValue(grp) == "GameData")
                        {
                            dataGroup = grp;
                            break;
                        }
                    }
                }

                // 如果不存在则创建 GameData 组
                if (dataGroup == null && groups != null)
                {
                    var groupType = GetType("YooAsset.Editor.AssetBundleCollectorGroup");
                    dataGroup = Activator.CreateInstance(groupType);
                    var nameField = groupType.GetField("GroupName", BindingFlags.Public | BindingFlags.Instance);
                    var descField = groupType.GetField("GroupDesc", BindingFlags.Public | BindingFlags.Instance);
                    var activeField = groupType.GetField("ActiveRuleName", BindingFlags.Public | BindingFlags.Instance);
                    nameField?.SetValue(dataGroup, "GameData");
                    descField?.SetValue(dataGroup, "Core Game Data");
                    activeField?.SetValue(dataGroup, "EnableGroup");
                    groups.Add(dataGroup);
                    Debug.Log("[ZeroEngine] Created 'GameData' Group");
                }

                // 获取 Collectors 列表
                var collectorsField = dataGroup?.GetType().GetField("Collectors", BindingFlags.Public | BindingFlags.Instance);
                var collectors = collectorsField?.GetValue(dataGroup) as IList;

                // 检查 Assets/Data 收集器是否存在
                bool hasDataCollector = false;
                if (collectors != null)
                {
                    foreach (var col in collectors)
                    {
                        var pathField = col.GetType().GetField("CollectPath", BindingFlags.Public | BindingFlags.Instance);
                        if (pathField != null && (string)pathField.GetValue(col) == "Assets/Data")
                        {
                            hasDataCollector = true;
                            break;
                        }
                    }
                }

                // 如果不存在则创建 Assets/Data 收集器
                if (!hasDataCollector && collectors != null)
                {
                    var collectorType = GetType("YooAsset.Editor.AssetBundleCollector");
                    var newCollector = Activator.CreateInstance(collectorType);

                    SetFieldValue(newCollector, "CollectPath", "Assets/Data");
                    SetFieldValue(newCollector, "CollectorGUID", AssetDatabase.AssetPathToGUID("Assets/Data"));
                    SetFieldValue(newCollector, "CollectorType", GetEnumValue("YooAsset.Editor.ECollectorType", "MainAssetCollector"));
                    SetFieldValue(newCollector, "AddressRuleName", "AddressByFileName");
                    SetFieldValue(newCollector, "PackRuleName", "PackDirectory");
                    SetFieldValue(newCollector, "FilterRuleName", "CollectAll");

                    collectors.Add(newCollector);
                    Debug.Log("[ZeroEngine] Added 'Assets/Data' Collector");
                }

                // 保存设置
                var saveMethod = settingDataType.GetMethod("SaveFile", BindingFlags.Public | BindingFlags.Static);
                saveMethod?.Invoke(null, null);

                Debug.Log("[ZeroEngine] ✅ YooAsset Configuration Complete!");
                Debug.Log("[ZeroEngine] Opening window to verify...");
                EditorApplication.ExecuteMenuItem("YooAsset/AssetBundle Collector");
            }
            catch (Exception ex)
            {
                Debug.LogError($"[ZeroEngine] Auto-config failed: {ex.Message}");
                Debug.Log("[ZeroEngine] Falling back to manual configuration...");
                Debug.Log("[ZeroEngine] Please manually add 'Assets/Data' as a Collector in the YooAsset window.");
                EditorApplication.ExecuteMenuItem("YooAsset/AssetBundle Collector");
            }
        }

        private static void SetFieldValue(object obj, string fieldName, object value)
        {
            var field = obj.GetType().GetField(fieldName, BindingFlags.Public | BindingFlags.Instance);
            if (field != null && value != null)
            {
                field.SetValue(obj, value);
            }
        }

        private static object GetEnumValue(string enumTypeName, string valueName)
        {
            var enumType = GetType(enumTypeName);
            if (enumType != null && enumType.IsEnum)
            {
                return Enum.Parse(enumType, valueName);
            }
            return null;
        }

        private static Type GetType(string typeName)
        {
            foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies())
            {
                var type = assembly.GetType(typeName);
                if (type != null) return type;
            }
            return null;
        }
    }
}
